### ISSUE TITLE
Shannon alpha diversity

### ISSUE THREAD

**Issue by sgaleraalq** [scikit-bio/scikit-bio#1884]
Good morning, 

I was comparing qiime2 (which uses scikit-bio tools) to calculate the alpha diversity using Shannon diversity metrics against the R package called "vegan" and I obtained different results. Getting into scikit documentation I found that your tools claims to calculate the diversity with this metric using the following formula:

![image](https://github.com/scikit-bio/scikit-bio/assets/114077560/406691d7-aa20-456d-a3a6-d0775b4e25c7)

And looking through your tools you have this peace of code:

```
@experimental(as_of="0.4.0")
def shannon(counts, base=2):
    r"""Calculate Shannon entropy of counts, default in bits.

    Shannon-Wiener diversity index is defined as:

    .. math::

       H = -\sum_{i=1}^s\left(p_i\log_2 p_i\right)

    where :math:`s` is the number of OTUs and :math:`p_i` is the proportion of
    the community represented by OTU :math:`i`.

    Parameters
    ----------
    counts : 1-D array_like, int
        Vector of counts.
    base : scalar, optional
        Logarithm base to use in the calculations.

    Returns
    -------
    double
        Shannon diversity index H.

    Notes
    -----
    The implementation here is based on the description given in the SDR-IV
    online manual [1]_ except that the default logarithm base used here is 2
    instead of :math:`e`.

    References
    ----------
    .. [1] http://www.pisces-conservation.com/sdrhelp/index.html

    """
    counts = _validate_counts_vector(counts)
    freqs = counts / counts.sum()
    nonzero_freqs = freqs[freqs.nonzero()]
    return -(nonzero_freqs * np.log(nonzero_freqs)).sum() / np.log(base)
```

Is the /np.log(base) a mistake? Because if I comment it, the results are more similar to the ones obtained using "vegan" in R.

Thank you very much.

**Comment by ebolyen** [comment]
What you are manipulating is the [change-of-base](https://en.wikipedia.org/wiki/List_of_logarithmic_identities#Changing_the_base) formula. 

There's no error here, as our formula is base 2 (bits/shannons), rather than base e (nats). 

By deleting the division you end up with the base as e, which is what Vegan prefers to use (hence why they match). The two different units are always a constant multiple of the other, so it's not usually a particularly interesting difference. 

To convert the alpha diversity from bits to nats (vegan), you could multiply all values by this constant:

```
In [1]: 1 / np.log2(np.e)
Out[1]: 0.6931471805599453
```

and to turn nats into bits you would use this constant:
```
In [2]: 1 / np.log(2)
Out[2]: 1.4426950408889634
```

These are inverses of each other, so multiplying by them both is the same as multiplying by 1.

**Comment by qiyunzhu** [comment]
@ebolyen I am wondering why the base was 2 in our implementation from the beginning? Most community ecology literatures I read use e instead of 2. In my impression, 2 is usually used in information theory (bits).
