### ISSUE TITLE
Slow unit test with `_enan.py`

### ISSUE THREAD

**Issue by qiyunzhu** [scikit-bio/scikit-bio#2072]
We experience several (not all) cases of `test_enan.py` being very slow. By reading the code, I am thinking whether such a patch is still needed in 2024. @mortonjt 

https://github.com/scikit-bio/scikit-bio/blob/main/skbio/metadata/_enan.py

**Comment by aryankeluskar** [comment]
Hello Qiyun, I recently started experiencing this as well. However, I believe the testcase slowing down the operation is in `class LotsaTestCase(unittest.TestCase):` since running `make test` on my local (MacOS, Apple Silicon) system is fine even after `test_enan.py` is complete. It encounters LotsaTestCase and remains stuck for 2-3 minutes. https://github.com/scikit-bio/scikit-bio/blob/0adae8f041b42c19f6c58eba7a10306aab9f725c/skbio/metadata/tests/test_intersection.py#L116-L166

**Comment by qiyunzhu** [comment]
@aryankeluskar Thank you for analyzing this! It is valuable information. @mortonjt

**Comment by qiyunzhu** [comment]
This test causes segmentation fault after long pause in some old software environments.

**Comment by qiyunzhu** [comment]
@mataton and I found the reason. It is related to #2061. We found a fix.
